# -*- coding: utf-8 -*-
"""Copy of Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KDGskdZzyM9Uy5na20uV06aRC5QWgInk
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/Attendance.csv")
(rows,cols) = df.shape
print(rows)
print(cols)

names = []
import csv

with open('/content/Attendance.csv') as file_obj:

    heading = next(file_obj)
      
    reader_obj = csv.reader(file_obj)

    for row in reader_obj:
        if row != []:
          names.append(row[0])

names

names = ["ramesh", "uma"]
details = []
final = []
for i in names:
  with open('/content/Agniveer_Dataset_test.csv') as file_obj:
    heading = next(file_obj)
    reader_obj = csv.reader(file_obj)
    for row in reader_obj:
      if row[0] == str(i):
        details.append(row[1:])

details

