# -*- coding: utf-8 -*-
"""Model_LOC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10nhgf7HuTkAmtMsA7_HioqRWKmbzyC0H
"""

from tensorflow.keras.models import load_model 
model=load_model("LOC.h5")

import pandas as pd
import numpy as np

df = pd.read_csv("C:\Users\nisha\OneDrive\Desktop\projects\LOC\Attendance\Attendance\Attendance.csv")
(rows,cols) = df.shape
print(rows)
print(cols)

names = []
import csv

with open('C:\Users\nisha\OneDrive\Desktop\projects\LOC\Attendance\Attendance\Attendance.csv') as file_obj:

    heading = next(file_obj)
      
    reader_obj = csv.reader(file_obj)

    for row in reader_obj:
        if row != []:
          names.append(row[0])
#
names = ["ramesh", "uma"]
details = []
final = []
for i in names:
  with open('C:\Users\nisha\OneDrive\Desktop\projects\LOC\Agniveer_Dataset_test.csv') as file_obj:
    heading = next(file_obj)
    reader_obj = csv.reader(file_obj)
    for row in reader_obj:
      if row[0] == str(i):
        details.append(row[1:])


pred = (model.predict(details))


final_list = []
x = []
final_index = []
m = []
import numpy as np

for i in range (10):
  b = "{0:.3f}".format(pred[0][i])
  final_list.append(float(b))
  m.append(float(b))
print(final_list)


for i in range (3):
  z = max(m)
  x.append(final_list.index(z))
  m.remove(z)
print(x)



jobs = []
for i in x:
    if i == 0:
        jobs.append("NCC Trainers")
    elif i == 1:
        jobs.append("Stenography")
    elif i == 2:
        jobs.append("Army Peon")
    elif i == 3:
        jobs.append("Army Vehicles Drivers")
    elif i == 4:
        jobs.append("Clerk")
    elif i == 5:
        jobs.append("RAW")
    elif i == 6:
        jobs.append("CID")
    elif i == 7:
        jobs.append("VIP BodyGuard")
    elif i == 8:
        jobs.append("Police")
    elif i == 9:
        jobs.append("Army Ground Staff")

print(jobs)

