# -*- coding: utf-8 -*-
"""Model_LOC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10nhgf7HuTkAmtMsA7_HioqRWKmbzyC0H
"""

from tensorflow.keras.models import load_model 
model=load_model("LOC.h5")
import streamlit as st 

import pandas as pd
import numpy as np

st.title("SHASWATH")
st.write("An elegant data driven career guidance system to suit the job hunting needs of Agniveers, after their service periods.")

df = pd.read_csv(r"C:\Users\nisha\OneDrive\Desktop\projects\LOC\Attendance\Attendance\Attendance.csv")
(rows,cols) = df.shape
print(rows)
print(cols)

names = []
import csv

with open(r'C:\Users\nisha\OneDrive\Desktop\projects\LOC\Attendance\Attendance\Attendance.csv') as file_obj:

    heading = next(file_obj)
      
    reader_obj = csv.reader(file_obj)

    for row in reader_obj:
        if row != []:
          names.append(row[0])

names = ["ramesh", "uma"]
details = []
final = []
for i in names:
  with open(r'C:\Users\nisha\OneDrive\Desktop\projects\LOC\Agniveer_Dataset_test.csv') as file_obj:
    heading = next(file_obj)#
    reader_obj = csv.reader(file_obj)
    for row in reader_obj:
      if row[0] == str(i):
        details.append(row[2:])

det=[[21, 64, 169, 118, 23, 10, 22, 86, 8, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0]] #

st.metric("Age",det[0][0])
st.metric("Weight",det[0][1])
st.metric("Height",det[0][2])
st.metric("Aptitude",det[0][3])
st.metric("MathsCEE",det[0][4])
st.metric("Logical Reasoning",det[0][5])
st.metric("GsCEE",det[0][6])
st.metric("BoardsEnglish",det[0][7])
st.metric("2km Run Time",det[0][8])
st.metric("Long Jump",det[0][9])
st.metric("High Jump",det[0][10])
st.metric("Beam Court",det[0][11])
st.metric("9 Feet Ditch",det[0][12])
st.metric("Zigzag M",det[0][13])
st.metric("Color Blind",det[0][14])
st.metric("Good Vision",det[0][15])
st.metric("Physically Unfit",det[0][16])
st.metric("Dental",det[0][17])
st.metric("Pressure Handling",det[0][18])

if st.button(label="JOB Suggestions"):
        pred = (model.predict(det))

        final_list = []
        x = []
        final_index = []
        m = []
        import numpy as np

        for i in range (10):
             b = "{0:.3f}".format(pred[0][i])
             final_list.append(float(b))
             m.append(float(b))
        print(final_list)


        for i in range (3):
             z = max(m)
             x.append(final_list.index(z))
             m.remove(z)
        print(x)



        jobs = []
        for i in x:
          if i == 0:
             jobs.append("NCC Trainers")
          elif i == 1:
              jobs.append("Stenography")
          elif i == 2:
              jobs.append("Army Peon")
          elif i == 3:
              jobs.append("Army Vehicles Drivers")
          elif i == 4:
              jobs.append("Clerk")
          elif i == 5:
              jobs.append("RAW")
          elif i == 6:
              jobs.append("CID")
          elif i == 7:
              jobs.append("VIP BodyGuard")
          elif i == 8:
              jobs.append("Police")
          elif i == 9:
              jobs.append("Army Ground Staff")

        fin =""
        for i in jobs:
          fin=fin+"    "+i+",    "
        st.success(fin)


